version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./config.env
    volumes:
      - .:/code
    ports:
      - "80:8000"
