# Generated by Django 3.1.4 on 2021-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_data',
            name='original_title',
            field=models.CharField(max_length=250),
        ),
    ]
